### ISSUE TITLE
Why tested in Lighthouse scrore is 82?

### ISSUE THREAD

**Issue by vanloc0301** [tastejs/hacker-news-pwas#46]
I don't know any reason. I tested with Lighthouse in Chrome Linux stable.

Score for Progressive Web App is 82.
![screenshot_2017-05-24_02-52-45](https://cloud.githubusercontent.com/assets/4168981/26373542/195880ea-402c-11e7-98a6-7397197b0f51.png)

**Comment by chrisdwheatley** [comment]
I'm seeing 91 on Chrome stable on macOS. It looks like the 'Page load is fast enough on 3G' test is failing, I'm imagining there can be some variance in this test due to network connectivity.

It could be that in your test the page loaded in just over 10 seconds whereas when tested for HNPWA the test was below 10 seconds. It could also be that there's some difference between Chrome on Linux and other operating systems, although I'm not sure what that would be.

It may be worth re-running the test and seeing if 82 was a one off or a consistent result for you.

**Comment by addyosmani** [comment]
The majority of apps currently on HNPWA.com are tested using Lighthouse 1.0 (in particular, running them on WebPageTest.org/easy). This used a different set of tests for interactivity (part of performance audits) than what you're seeing above in Lighthouse 2.0. 

We'll be switching our own reporting over to Lighthouse 2.0 once the WebPageTest integration with it has stabilized. Right now we've evaluated a number of apps and found that there are quite a few times when LH 2.0 fails to correctly capture interactivity, leading to incorrect scoring. The Lighthouse team have filed some fixes for this and we're going to take another look at the disparity once the next release (2.0.x) gets rolled out.

I'll be closing this issue as it's a known WIP but we appreciate you checking in about this!

**Comment by vanloc0301** [comment]
I know the problem. Thanks for your explain @addyosmani @chrisdwheatley
